# Base configs
baseurl: "https://semir-t.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Semir Tursunovic"
subtitle: "See the world through my eyes!"
author: "Semir Tursunovic"
header:
 title: "Photography"
 subtitle: "by Semir Tursunovic"
footer:
 name: ""
 bio: ""
 github: ""
web_design: "AJ"
social_urls:
  instagram: "https://www.github.com/semir-t"
  dribbble: "https://www.github.com/semir-t"
  linkedin: "https://www.github.com/semir-t"
  github: "https://www.github.com/semir-t"
