- name: Image Resizer Action
  uses: sharadcodes/img-resizer@v1.1
  with:
    image-folder: 'my_images' # This is a Required field & this folder has original images
    new-resolution: '400x200' # This is Required field
    output-folder: "my_resized_images" # This is Required field & this folder will be used to store resized images
