  name: Image Resizer Action
  on:
    push:

  jobs:
    resize:
      runs-on: ubuntu-latest
      steps:
        - name: Image Resizer Action
          uses: sharadcodes/img-resizer@v1.1
          with:
            image-folder: 'photography/images/fulls' # This is a Required field & this folder has original images
            new-resolution: '512x341' # This is Required field
            output-folder: "photography/images/thumbs" # This is Required field & this folder will be used to store resized images




